apiVersion: v1
kind: ConfigMap
metadata:
  name: web-app
data:
  index.html:
  style.css:

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-deployment
spec:
  replicas: 3  # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: web-app
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: web-app-files
          mountPath: /usr/share/nginx/html
  volumes:
  - name: web-app-files
    configMap:
      name: web-app